package br.com.sorveteria.tela;

import java.awt.Desktop;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author KCSilva
 */
public class TelaPrincipal extends javax.swing.JFrame {

   
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuVendasSorvete = new javax.swing.JMenuBar();
        menuModulos = new javax.swing.JMenu();
        itemCadastrarCliente = new javax.swing.JMenuItem();
        itemCadastrarSorvete = new javax.swing.JMenuItem();
        itemCadastrarSetor = new javax.swing.JMenuItem();
        itemVenderSorvetes = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        itemMenuRelatorioClientes = new javax.swing.JMenu();
        itemRelatorioVendasClientes = new javax.swing.JMenuItem();
        itemRelatorioVendasSorvetes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sorveteria");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuModulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteria/imagens/application.png"))); // NOI18N
        menuModulos.setText("Módulos");

        itemCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteria/imagens/user.png"))); // NOI18N
        itemCadastrarCliente.setText("Cadastrar Cliente");
        itemCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarClienteActionPerformed(evt);
            }
        });
        menuModulos.add(itemCadastrarCliente);

        itemCadastrarSorvete.setText("Cadastrar Sorvete");
        itemCadastrarSorvete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarSorveteActionPerformed(evt);
            }
        });
        menuModulos.add(itemCadastrarSorvete);

        itemCadastrarSetor.setText("Cadastrar Setor");
        itemCadastrarSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarSetorActionPerformed(evt);
            }
        });
        menuModulos.add(itemCadastrarSetor);

        itemVenderSorvetes.setText("Vender Sorvete");
        menuModulos.add(itemVenderSorvetes);

        menuVendasSorvete.add(menuModulos);

        menuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sorveteria/imagens/page.png"))); // NOI18N
        menuRelatorio.setText("Relatórios");

        itemMenuRelatorioClientes.setText("Sorvetes");

        itemRelatorioVendasClientes.setText("Relatório Vendas Sorvetes");
        itemMenuRelatorioClientes.add(itemRelatorioVendasClientes);
        itemMenuRelatorioClientes.add(itemRelatorioVendasSorvetes);

        menuRelatorio.add(itemMenuRelatorioClientes);

        jMenu2.setText("Clientes");

        jMenuItem3.setText("Relatório Vendas Clientes");
        jMenu2.add(jMenuItem3);

        menuRelatorio.add(jMenu2);

        menuVendasSorvete.add(menuRelatorio);

        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/door_out.png"))); // NOI18N
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuVendasSorvete.add(menuSair);

        setJMenuBar(menuVendasSorvete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarClienteActionPerformed
        // Criando variavel de referencia telaCadUser
        TelaCadastroCliente telaCadUser = new TelaCadastroCliente();
        // Adicionando telaCadUser ao Painel da area de trabalho
        jDesktopPane1.add(telaCadUser);
        // Mostrando a tela de cadastro ao clicar em cadastrar cliente.
        telaCadUser.setVisible(true);
        // Invocando Método para centralizar MDI
        telaCadUser.setPosicao();
    }//GEN-LAST:event_itemCadastrarClienteActionPerformed

    private void itemCadastrarSorveteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarSorveteActionPerformed
        TelaCadastroSorvete telaCadSorvete = new TelaCadastroSorvete();
        jDesktopPane1.add(telaCadSorvete);
        telaCadSorvete.setVisible(true);
        telaCadSorvete.setPosicao();
        
    }//GEN-LAST:event_itemCadastrarSorveteActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed

    }//GEN-LAST:event_menuSairActionPerformed

    private void itemCadastrarSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarSetorActionPerformed
        TelaCadastroSetor telaCadSetor = new TelaCadastroSetor();
        jDesktopPane1.add(telaCadSetor);
        telaCadSetor.setVisible(true);
        telaCadSetor.setPosicao();    
    }//GEN-LAST:event_itemCadastrarSetorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCadastrarCliente;
    private javax.swing.JMenuItem itemCadastrarSetor;
    private javax.swing.JMenuItem itemCadastrarSorvete;
    private javax.swing.JMenu itemMenuRelatorioClientes;
    private javax.swing.JMenuItem itemRelatorioVendasClientes;
    private javax.swing.JMenuItem itemRelatorioVendasSorvetes;
    private javax.swing.JMenuItem itemVenderSorvetes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuModulos;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuBar menuVendasSorvete;
    // End of variables declaration//GEN-END:variables
}
